# Generated by Django 5.2.2 on 2025-06-04 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customuser_specialty'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_grade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('confidence_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prediction_date', models.DateTimeField(auto_now_add=True)),
                ('semester', models.CharField(max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('features_used', models.JSONField()),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
            ],
            options={
                'ordering': ['-prediction_date'],
            },
        ),
        migrations.CreateModel(
            name='ParticipationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('participation_type', models.CharField(choices=[('QUESTION', 'Pregunta'), ('ANSWER', 'Respuesta'), ('DISCUSSION', 'Participación en Discusión'), ('PRESENTATION', 'Presentación'), ('GROUP_WORK', 'Trabajo en Grupo')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('quality_score', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
