# Generated by Django 5.2.2 on 2025-06-05 03:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_academicprediction_participationrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachersubject',
            options={'verbose_name': 'Asignación de Materia a Profesor', 'verbose_name_plural': 'Asignaciones de Materias a Profesores'},
        ),
        migrations.AlterField(
            model_name='teachersubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_subjects', to='core.subject'),
        ),
        migrations.AlterField(
            model_name='teachersubject',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_subjects', to=settings.AUTH_USER_MODEL),
        ),
    ]
