# Generated by Django 5.2.2 on 2025-06-05 04:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_teachersubject_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicprediction',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='academicprediction',
            old_name='prediction_date',
            new_name='created_at',
        ),
        migrations.AlterUniqueTogether(
            name='academicprediction',
            unique_together={('student', 'subject')},
        ),
        migrations.AddField(
            model_name='academicprediction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='academicprediction',
            name='predicted_grade',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='academicprediction',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='academicprediction',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='core.subject'),
        ),
        migrations.RemoveField(
            model_name='academicprediction',
            name='features_used',
        ),
        migrations.RemoveField(
            model_name='academicprediction',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='academicprediction',
            name='year',
        ),
    ]
